name = input("enter your name: ")
surname = input("enter your surname: ")
mom_name = input("enter your mom's name: ")
mom_surname = input("enter your mom's sunmae: ")
dad_name = input("enter your dad's name: ")
dad_surname = input("enter your dad's surname: ")
color = input("enter your favourite color: ")
car = input("enter your favourite car: ")
hobby1, hobby2, hobby3 = input("enter your three favourite hobbys: ").split()

print(name, surname, mom_name, mom_surname, dad_name, dad_surname, color, car, hobby1, hobby2, hobby3,)
