const div1 = document.createElement("div1")
const div2 = document.createElement("div1")
const div3 = document.createElement("div1")
document.body.append(div1)
document.body.append(div2)
document.body.append(div3)
document.body.removeChild(div1)
document.body.removeChild(div2)
document.body.removeChild(div3)